import "./About.css"
function About() {
    return (
         <>
           <div className="container-about">
            <p className="para-2">Dibrugarh University is a university in the Indian state of Assam. It was set up in 1965 under the provisions of the Dibrugarh University Act, 1965,[1] enacted by the Assam Legislative Assembly. It is a teaching-cum-affiliating university.</p>
            <p className="para-2">Location and Campus<br/>The Dibrugarh University Campus is located at Rajabheta, 5 km from Dibrugarh Town (27° 29′ North Latitude and 94° 55′ East Longitude) and is spread over an area of 500 acres.[2] The NH15 (old NH37) bisects the main campus from the other, the latter primarily comprising teacher’s and officer’s residence.</p>
            <p className="para-2">The Dibrugarh district is well known for its vast mineral resources (including oil, natural gas and coal), flora and fauna and many tea plantations. The diverse tribes with their distinct dialects, customs, traditions and culture make this area attractive to students of anthropology and sociology, art and culture.</p>
            <p className="para-2">Accreditation<br/>It is accredited by the National Assessment and Accreditation Council, with an ‘A’ Grade in 2017.[3] This accreditation status is valid for a period of five years.[4] Dibrugarh University is a member of the Association of Indian Universities (AIU)[5] and the Association of Commonwealth Universities (ACU).[6]</p>
            <p className="para-2">Academics</p>
            <p className="para-2">Centre for Computer Studies</p>
            <p className="para-2">Administrative Office of the University<br/>The Centre for Computer Studies (CCS) originates in a Computer Centre established in 1976, which taught a “Six-month Certificate Course on Computer Programming”. In 2004 it was upgraded to the Centre for Computer Studies and started “Post-Graduate Diploma in Computer Application (PGDCA)”. BCA was introduced in July 2004 and MCA and B.Sc IT in January and July 2007. The center has three computer laboratories as well as its own library.</p>
            <p className="para-2">The MCA programme of CCS is approved by All India Council for Technical Education (AICTE). It is also an accredited study centre for Indira Gandhi National Open University.</p>
            <p className="para-2">Admission to CCS is based on a state level Common Admission Test (CAT). Candidates are then called for a personal interview, counseling and admission. In addition, some programmes have requirements for passing 10+2 level with mathematics and/or statistics at some threshold mark in aggregate.</p>
            <p className="para-2">Dibrugarh University Institute of Engineering and Technology<br/>The Dibrugarh University Institute of Engineering and Technology (DUIET) was established in 2009 as a constituent institute and an integral part the university. The institute was established with due approval from the All India Council for Technical Education (AICTE), New Delhi and necessary permission from the Assam state government.</p>
            <p className="para-2">The first session of the institute commenced in August 2009 with an intake capacity of 60 in each of the following disciplines to a B. Tech. degree:</p>
            <p className="para-2">Electronics and Communication Engineering<br/>Computer Science and Engineering<br/>Petroleum Engineering<br/>Mechanical Engineering<br/>DUIET is located in the Dibrugarh University campus. It has excellent infrastructure and facilities. The administration of DUIET is headed by Dr. M.C.Bora who is the institute director.</p>
            <p className="para-2">Centre for Management Studies<br/>The Centre for Management Studies (CMSDU) is a management school that is part of Dibrugarh University. It started functioning from 3 February 2003, with the first batch of Master of Business Administration (MBA) students enrolled into the two-year programme.[citation needed] The three-year Bachelor of Business Administration (BBA) and the three-year MBA (part-time) classes started in 2004.[citation needed] 2006 saw the launch of the one-year PGDTM (Post Graduate Diploma in Tourism Management) Programme.[citation needed] It is also running a Ph.D. programme which can be pursued both part-time as well as full-time.</p>
            <p className="para-2">Centre for Juridical Studies<br/>The centre for juridical studies is a Centre of Dibrugarh University that imparts both undergraduate and Post Graduate legal education. The centre was established in the year 2006. The Centre runs BALL.B (H)and LL.M (Constitutional Law, Corporate Law and Criminal Law Groups) courses.[7]</p>
            <p className="para-2">Eligibility: For B.A.LL.B. (H): A candidate for admission to the Five- year B.A.LL.B. (Hons) Course shall have passed the Higher Secondary Examination (10+2) or an equivalent examination securing at least 45% in aggregate of the total marks. Provided that there shall be a relaxation of 5% marks for SC/ST/OBC candidates. For LL.M.: A candidate to take admission into LL.M. Course must have 50% marks in aggregate in 3 year LL.B. or 5 year B.A.LL.B. (H) Course recognized by University Grants Commission (UGC) and Bar Council of India (BCI). The candidates appearing in final year examination of the aforesaid Programmes may also apply but at the time of admission they must produce the mark sheet and pass Certificate in original.</p>
            <p className="para-2">Admission Procedure: The admission to the aforesaid Programmes will be made only on merit basis through an Admission Test and (viva-voce/wherever applicable) to be conducted by the University. Admission cannot be claimed by any applicant as a matter of right. Note: In case of LL.M only, on being selected for admission, the applicant has to appear before admission committee at the Centre for Juridical Studies, Dibrugarh University with all original certificates, mark sheets and other requirements on scheduled date and time. If any selected candidate is unable to appear personally, he may send his authorized representative with the required documents. If any applicant fails to deposit prescribed fee within the stipulated time, his/her admission will automatically stand cancelled. If any selected candidate or his authorised representative does not appear before Admission Committee on scheduled date and time, his/her candidature shall be deemed to be cancelled without any intimation in writing.[7]</p>
            <p className="para-2">Dibrugarh University was ranked in the 101–150 band overall in India by the National Institutional Ranking Framework (NIRF) in 2019,[12] 86 among universities[13] and 35 in the pharmacy ranking.[11]</p>
         
            
             </div>
            </>
                )
  }


  export default About;